# Docker compose file for setting up development environment container.
# Builds and sets up development container for example service.
# Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3.9"

services:
  example-dev:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
